# IMSI number of the UE (must match subscriber in Open5GS)
supi: 'imsi-001010000000001'

# Mobile Country Code
mcc: '001'

# Mobile Network Code
mnc: '01'

# Permanent subscription key (K)
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'

# Operator code (OPc)
op: 'E8ED289DEBA952E4283B54E88E6183CA'

# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'

# Authentication Management Field (AMF) value
amf: '8000'

# IMEI number of the device
imei: '356938035643803'

# IMEISV number of the device
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 192.168.139.140

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    dnn: 'internet'
    slice:
      sst: 1

# Configured NSSAI for this UE
configured-nssai:
  - sst: 1
#  - sst: 2

# Default configured NSSAI for this UE
default-nssai:
  - sst: 1

# Integrity protection maximum data rate for user plane
integrity:
  IA1: true
  IA2: true
  IA3: true

# Ciphering algorithms
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Supported bands
bands:
  - 78  # n78 band (3500 MHz)
integrityMaxRate:
  uplink: full
  downlink: full
